export const CATEGORIES = [
    "All",
    "Earbuds",
    "Smartwatch",
    "Keyboard",
    "Gaming",
    "Power",
    "Accessories",
    "Webcam",
];

export const gadgets = [
    {
        id: "sony-wf1000xm5",
        title: "Sony WF-1000XM5",
        shortDescription: "Industry-leading noise cancellation in a compact form.",
        fullDescription:
            "The Sony WF-1000XM5 sets the gold standard for wireless earbuds. Powered by the QN2e processor, it delivers the most precise noise cancellation Sony has ever put into earbuds. The 8.4mm driver produces expansive sound with deep bass, clear mids, and sparkling highs. LDAC support streams Hi-Res Audio at up to 990kbps over Bluetooth. Speak-to-Chat automatically pauses music when you start talking, and multipoint connection lets you switch seamlessly between two devices.",
        category: "Earbuds",
        price: 279.99,
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80",
        brand: "Sony",
        specs: {
            Connectivity: "Bluetooth 5.3",
            "Battery Life": "8h + 16h case",
            "Noise Cancellation": "QN2e Processor",
            "Driver Size": "8.4mm",
            Weight: "5.9g per earbud",
            Codec: "LDAC, AAC, SBC",
            "Water Resistance": "IPX4",
        },
        createdAt: "2025-01-10",
    },
    {
        id: "apple-watch-ultra2",
        title: "Apple Watch Ultra 2",
        shortDescription: "The most rugged and capable Apple Watch ever made.",
        fullDescription:
            "Built for endurance athletes and adventurers, the Apple Watch Ultra 2 pushes performance to the limit. A 49mm titanium case surrounds the brightest Apple Watch display at 3000 nits, readable in direct sunlight. The dual-frequency GPS provides pinpoint accuracy even in dense canyon terrain. With an 18-hour battery life that extends to 60 hours in Low Power Mode, it will outlast your toughest training days.",
        category: "Smartwatch",
        price: 799.0,
        rating: 4.9,
        imageUrl: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&q=80",
        brand: "Apple",
        specs: {
            Case: "49mm Titanium",
            Display: "3000 nit Always-On Retina",
            Battery: "18h (60h Low Power)",
            GPS: "L1 + L5 Dual Frequency",
            "Water Resistance": "100m",
            Processor: "S9 SiP",
            OS: "watchOS 11",
        },
        createdAt: "2025-01-15",
    },
    {
        id: "keychron-q3-max",
        title: "Keychron Q3 Max",
        shortDescription: "Full aluminum TKL with gasket mount and wireless.",
        fullDescription:
            "The Keychron Q3 Max is the wireless evolution of the beloved Q3 mechanical keyboard. A full CNC-machined aluminum body with a gasket mounting system absorbs the sound and bounce of every keystroke. The south-facing RGB LEDs maximize shine-through on keycaps, and QMK/VIA compatibility means your layout is infinitely customizable. Bluetooth 5.1 connects up to three devices with a single key shortcut.",
        category: "Keyboard",
        price: 199.0,
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
        brand: "Keychron",
        specs: {
            Layout: "TKL (80%)",
            "Mount Type": "Gasket",
            Connectivity: "Bluetooth 5.1 / USB-C",
            Switches: "K Pro Red / Brown / Blue",
            Material: "CNC Aluminum",
            Backlight: "South-facing RGB",
            Battery: "4000mAh",
        },
        createdAt: "2025-01-20",
    },
    {
        id: "razer-deathadder-v3",
        title: "Razer DeathAdder V3",
        shortDescription: "Ergonomic wireless gaming mouse with 90-hour battery.",
        fullDescription:
            "The Razer DeathAdder V3 HyperSpeed is the wireless version of the world's most popular gaming mouse. At just 81g it retains the iconic ergonomic right-handed shape that millions of players trust. The Focus X 26K optical sensor tracks at up to 26,000 DPI with zero smoothing or acceleration. HyperSpeed wireless technology reduces latency to be on par with wired performance.",
        category: "Gaming",
        price: 99.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=600&q=80",
        brand: "Razer",
        specs: {
            Sensor: "Focus X 26K",
            DPI: "100 – 26,000",
            Connectivity: "HyperSpeed Wireless / USB-C",
            Weight: "81g",
            Battery: "90 hours",
            Buttons: "6 programmable",
            Switches: "3rd Gen Mechanical",
        },
        createdAt: "2025-02-01",
    },
    {
        id: "anker-prime-powerbank",
        title: "Anker Prime 27,650mAh",
        shortDescription: "200W total output power bank for laptops and phones.",
        fullDescription:
            "The Anker Prime is the first power bank capable of delivering 200W of total output power — enough to charge a MacBook Pro at full speed while simultaneously topping up your phone and earbuds. Its 27,650mAh capacity can fill a standard 13-inch laptop twice over. The built-in display shows exact wattage input and output in real time so you always know what's happening.",
        category: "Power",
        price: 149.99,
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80",
        brand: "Anker",
        specs: {
            Capacity: "27,650mAh / 99.35Wh",
            "Max Output": "200W Total",
            Ports: "2× USB-C, 1× USB-A",
            Input: "170W Max",
            Technology: "GaN, ActiveShield 2.0",
            Display: "Smart Digital Display",
            Weight: "652g",
        },
        createdAt: "2025-02-10",
    },
    {
        id: "logitech-brio-505",
        title: "Logitech Brio 505",
        shortDescription: "Full HD webcam with auto-light correction and privacy shutter.",
        fullDescription:
            "The Logitech Brio 505 is engineered for professionals who work from anywhere. Its auto-light balance automatically adjusts exposure in real time. The 90° adjustable field of view lets you frame yourself or include a whiteboard. Show Mode flips the camera 180° to share documents on your desk during calls.",
        category: "Webcam",
        price: 129.99,
        rating: 4.5,
        imageUrl: "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=600&q=80",
        brand: "Logitech",
        specs: {
            Resolution: "1080p / 60fps",
            "Field of View": "65°–90° adjustable",
            "Auto Focus": "AI-powered",
            Microphone: "RightSound dual-mic",
            Connection: "USB-C",
            Privacy: "Built-in shutter",
            Compatibility: "Windows, macOS, ChromeOS",
        },
        createdAt: "2025-02-18",
    },
    {
        id: "samsung-galaxy-buds3-pro",
        title: "Samsung Galaxy Buds3 Pro",
        shortDescription: "Open-canal design with intelligent ANC and 360 Audio.",
        fullDescription:
            "Samsung's Galaxy Buds3 Pro reinvent the premium earbud with a blade-inspired open-canal design. Intelligent Active Noise Cancellation analyzes your environment 240 times per second. 360 Audio with head tracking follows the motion of your head for a true spatial listening experience.",
        category: "Earbuds",
        price: 249.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80",
        brand: "Samsung",
        specs: {
            Design: "Open-canal blade",
            Driver: "10.5mm two-way",
            "Battery Life": "6h + 18h case",
            ANC: "Intelligent ANC 3.0",
            Codec: "SSC HiFi, AAC, SBC",
            "Water Resistance": "IPX7",
            Connectivity: "Bluetooth 5.4",
        },
        createdAt: "2025-03-01",
    },
    {
        id: "elgato-stream-deck-mk2",
        title: "Elgato Stream Deck MK.2",
        shortDescription: "15 LCD keys to control your stream, apps, and workflow.",
        fullDescription:
            "The Elgato Stream Deck MK.2 puts 15 customizable LCD keys at your fingertips. Each key can show any icon or image and trigger any action with a single tap. Unlimited page nesting means you can store hundreds of actions across themed pages.",
        category: "Accessories",
        price: 149.99,
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=600&q=80",
        brand: "Elgato",
        specs: {
            Keys: "15 customizable LCD",
            Resolution: "72×72px per key",
            Connection: "USB-C",
            Compatibility: "Windows 10+, macOS 10.15+",
            Software: "Stream Deck Software",
            Stand: "Adjustable, reversible",
            Dimensions: "118×84×21mm",
        },
        createdAt: "2025-03-10",
    },
    {
        id: "garmin-forerunner-965",
        title: "Garmin Forerunner 965",
        shortDescription: "Premium AMOLED running smartwatch with full triathlon support.",
        fullDescription:
            "The Garmin Forerunner 965 is built for athletes who demand data. The vibrant AMOLED display is always on without sacrificing the 31-day battery life. Training Readiness synthesizes your sleep, HRV, and recent training load into a single daily score.",
        category: "Smartwatch",
        price: 599.99,
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1523475496153-3e2b9b518c5f?w=600&q=80",
        brand: "Garmin",
        specs: {
            Display: "AMOLED Always-On",
            Battery: "31 days / 19h GPS",
            GPS: "Multi-band GNSS",
            "Health Sensors": "HRV, SpO2, Pulse Ox",
            "Water Resistance": "100m",
            Storage: "32GB music",
            Weight: "53g",
        },
        createdAt: "2025-03-15",
    },
    {
        id: "steelseries-arctis-nova-pro",
        title: "SteelSeries Arctis Nova Pro",
        shortDescription: "Hi-Fi gaming headset with active noise cancellation.",
        fullDescription:
            "The SteelSeries Arctis Nova Pro is the most technically advanced gaming headset SteelSeries has ever produced. High-fidelity 40mm neodymium drivers cover the full 10–40,000Hz spectrum. The hot-swap battery system means you will never be pulled out of a game to charge.",
        category: "Gaming",
        price: 349.99,
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1599669454699-248893623440?w=600&q=80",
        brand: "SteelSeries",
        specs: {
            Drivers: "40mm Hi-Fi neodymium",
            "Frequency Response": "10–40,000Hz",
            ANC: "Active Noise Cancellation",
            Connectivity: "Bluetooth 5.0 + 2.4GHz",
            Battery: "Hot-swap dual battery",
            Microphone: "ClearCast Gen 2 retractable",
            Weight: "338g",
        },
        createdAt: "2025-03-20",
    },
    {
        id: "jabra-evolve2-85",
        title: "Jabra Evolve2 85",
        shortDescription: "Professional wireless headset built for open offices.",
        fullDescription:
            "The Jabra Evolve2 85 is designed for professionals who need to focus in noisy environments. Ten microphones deliver advanced ANC while the 40mm speaker units produce rich, natural audio. The FlexBoom microphone rotates to signal availability to colleagues and the 37-hour battery powers through the longest workdays.",
        category: "Earbuds",
        price: 449.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
        brand: "Jabra",
        specs: {
            Microphones: "10-mic array",
            Battery: "37 hours",
            Connectivity: "Bluetooth 5.0 / USB",
            ANC: "Advanced Hybrid ANC",
            Drivers: "40mm",
            Weight: "341g",
            Certification: "Microsoft Teams",
        },
        createdAt: "2025-03-25",
    },
    {
        id: "samsung-galaxy-watch7",
        title: "Samsung Galaxy Watch 7",
        shortDescription: "Advanced health tracking with BioActive sensor.",
        fullDescription:
            "The Samsung Galaxy Watch 7 packs the most advanced sensor suite Samsung has ever built into a watch. The BioActive sensor tracks heart rate, ECG, blood oxygen, and body composition simultaneously. A new 3nm processor delivers 30% better performance than its predecessor while the improved battery lasts up to 40 hours.",
        category: "Smartwatch",
        price: 299.99,
        rating: 4.5,
        imageUrl: "https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=600&q=80",
        brand: "Samsung",
        specs: {
            Display: "Super AMOLED 1.3in",
            Battery: "40h / 3 days AOD off",
            Processor: "Exynos W1000 3nm",
            Sensors: "BioActive, ECG, GPS",
            "Water Resistance": "5ATM + IP68",
            OS: "Wear OS + One UI Watch 6",
            Weight: "28.9g",
        },
        createdAt: "2025-04-01",
    },
    {
        id: "logitech-mx-keys-s",
        title: "Logitech MX Keys S",
        shortDescription: "Smart illuminated keyboard for productivity and comfort.",
        fullDescription:
            "The Logitech MX Keys S is the evolution of the most popular advanced keyboard for professionals. Perfectly spherical keys match the shape of your fingertips for a precise, comfortable typing experience. Smart backlighting adapts to ambient light and activates only when your hands approach. Connect to three devices simultaneously via Bluetooth or USB receiver.",
        category: "Keyboard",
        price: 109.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80",
        brand: "Logitech",
        specs: {
            Layout: "Full-size",
            Connectivity: "Bluetooth / Logi Bolt USB",
            Backlight: "Smart adaptive",
            Battery: "10 days (backlit) / 5 months",
            "Multi-Device": "3 devices",
            Keys: "Spherical dish keys",
            Compatibility: "Windows, macOS, Linux",
        },
        createdAt: "2025-04-05",
    },
    {
        id: "corsair-k100-rgb",
        title: "Corsair K100 RGB",
        shortDescription: "Flagship optical-mechanical gaming keyboard.",
        fullDescription:
            "The Corsair K100 RGB is Corsair's most advanced gaming keyboard ever. OPX optical-mechanical switches actuate at the speed of light with a 1mm actuation point and 45g actuation force for the fastest possible key registration. The iCUE control wheel provides instant access to lighting effects, media controls, and macro assignments without leaving your game.",
        category: "Keyboard",
        price: 229.99,
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&q=80",
        brand: "Corsair",
        specs: {
            Switches: "OPX Optical-Mechanical",
            "Actuation Point": "1mm",
            Polling: "4000Hz hyper-polling",
            RGB: "44-zone per-key",
            Memory: "8MB onboard",
            Cable: "Braided detachable",
            "Special Feature": "iCUE Control Wheel",
        },
        createdAt: "2025-04-10",
    },
    {
        id: "logitech-g-pro-x2",
        title: "Logitech G Pro X 2 Lightspeed",
        shortDescription: "Ultra-lightweight pro wireless gaming mouse at 60g.",
        fullDescription:
            "The Logitech G Pro X 2 Lightspeed is engineered with professional esports athletes. At just 60g it is among the lightest wireless gaming mice available. The HERO 25K sensor delivers exceptional accuracy at any sensitivity with zero smoothing or filtering. Lightspeed wireless technology provides a sub-1ms connection that rivals wired performance.",
        category: "Gaming",
        price: 159.99,
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&q=80",
        brand: "Logitech",
        specs: {
            Sensor: "HERO 25K",
            Weight: "60g",
            Battery: "95 hours",
            Connectivity: "Lightspeed / Bluetooth / USB-C",
            DPI: "100–25,600",
            Buttons: "5 programmable",
            Feet: "PTFE",
        },
        createdAt: "2025-04-15",
    },
    {
        id: "anker-736-charger",
        title: "Anker 736 Nano II 100W",
        shortDescription: "Compact 3-port 100W GaN charger for all your devices.",
        fullDescription:
            "The Anker 736 Nano II charges laptops, tablets, and phones simultaneously from a single wall outlet. GaN II technology allows the charger to run cooler and pack more power into a smaller form factor than traditional chargers. ActiveShield 2.0 monitors device temperature and adjusts charging speed to protect your devices.",
        category: "Power",
        price: 55.99,
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
        brand: "Anker",
        specs: {
            "Total Output": "100W",
            Ports: "2× USB-C, 1× USB-A",
            Technology: "GaN II",
            "Single Port Max": "100W",
            Safety: "ActiveShield 2.0",
            Size: "Compact foldable",
            Compatibility: "Universal",
        },
        createdAt: "2025-04-20",
    },
    {
        id: "bose-quietcomfort-ultra",
        title: "Bose QuietComfort Ultra",
        shortDescription: "World-class noise cancellation meets immersive audio.",
        fullDescription:
            "The Bose QuietComfort Ultra Earbuds represent the pinnacle of Bose audio engineering. CustomTune technology measures your unique ear geometry and adjusts both sound and ANC performance in real time. Immersive Audio places sound outside your head for a spatial listening experience. The secure and comfortable wing tip design keeps them in place during workouts.",
        category: "Earbuds",
        price: 299.99,
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=600&q=80",
        brand: "Bose",
        specs: {
            ANC: "CustomTune Adaptive",
            "Battery Life": "6h + 18h case",
            Audio: "Immersive Spatial Audio",
            Connectivity: "Bluetooth 5.3",
            "Water Resistance": "IPX4",
            Fit: "Secure wing tip",
            Weight: "6.2g per earbud",
        },
        createdAt: "2025-04-25",
    },
    {
        id: "elgato-facecam-pro",
        title: "Elgato Facecam Pro",
        shortDescription: "4K60 webcam with Sony STARVIS sensor for streamers.",
        fullDescription:
            "The Elgato Facecam Pro is built for content creators who demand the highest image quality. A Sony STARVIS sensor captures 4K at 60fps with exceptional low-light performance. The fixed focus prime lens delivers sharp, cinematic depth of field. Camera Hub software gives you full manual control over every setting from ISO to white balance.",
        category: "Webcam",
        price: 299.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1620287341056-49a2f1ab2fdc?w=600&q=80",
        brand: "Elgato",
        specs: {
            Resolution: "4K / 60fps",
            Sensor: "Sony STARVIS",
            Lens: "Fixed focus prime",
            "Low Light": "Exceptional STARVIS",
            Connection: "USB-C 3.0",
            Software: "Camera Hub",
            Mounting: "Universal clip / tripod",
        },
        createdAt: "2025-05-01",
    },
    {
        id: "apple-airpods-pro2",
        title: "Apple AirPods Pro 2",
        shortDescription: "H2 chip ANC earbuds with Adaptive Audio.",
        fullDescription:
            "The Apple AirPods Pro 2nd generation are powered by the H2 chip for computational audio that updates 48,000 times per second. Adaptive Audio seamlessly blends Active Noise Cancellation and Transparency mode based on your environment. Personalized Spatial Audio with dynamic head tracking places sound all around you using your unique ear and head shape.",
        category: "Earbuds",
        price: 249.0,
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&q=80",
        brand: "Apple",
        specs: {
            Chip: "Apple H2",
            ANC: "Adaptive Audio",
            "Battery Life": "6h + 30h case",
            Audio: "Personalized Spatial Audio",
            Connectivity: "Bluetooth 5.3",
            "Water Resistance": "IPX4",
            "Find My": "Built-in speaker",
        },
        createdAt: "2025-05-05",
    },
    {
        id: "razer-blackwidow-v4-pro",
        title: "Razer BlackWidow V4 Pro",
        shortDescription: "Wireless mechanical keyboard with Razer Chroma RGB.",
        fullDescription:
            "The Razer BlackWidow V4 Pro brings premium wireless performance to Razer's legendary gaming keyboard line. Razer Yellow mechanical switches deliver fast linear actuation with near-silent operation. HyperSpeed wireless at 1000Hz polling rate ensures zero latency. The magnetic wrist rest and multi-function roller add ergonomic comfort and workflow control.",
        category: "Keyboard",
        price: 249.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1595044426077-d36d9236d54a?w=600&q=80",
        brand: "Razer",
        specs: {
            Switches: "Razer Yellow V3",
            Connectivity: "HyperSpeed 2.4GHz / BT / USB",
            Polling: "1000Hz wireless",
            Battery: "200 hours",
            RGB: "Razer Chroma per-key",
            Layout: "Full-size",
            "Special Feature": "Multi-function roller",
        },
        createdAt: "2025-05-10",
    },
    {
        id: "samsung-t7-shield",
        title: "Samsung T7 Shield 2TB",
        shortDescription: "Rugged portable SSD with IP65 dust and water resistance.",
        fullDescription:
            "The Samsung T7 Shield is the toughest portable SSD Samsung has ever made. IP65 certification protects against dust and water jets while the dynamic rugged exterior absorbs drops from up to 3 meters. Read speeds of up to 1,050 MB/s let you transfer a 4K video file in seconds. AES 256-bit hardware encryption keeps your data secure.",
        category: "Accessories",
        price: 179.99,
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=600&q=80",
        brand: "Samsung",
        specs: {
            Capacity: "2TB",
            "Read Speed": "1,050 MB/s",
            "Write Speed": "1,000 MB/s",
            "Drop Resistance": "3 meters",
            "Water Resistance": "IP65",
            Encryption: "AES 256-bit",
            Interface: "USB 3.2 Gen 2",
        },
        createdAt: "2025-05-12",
    },
    {
        id: "pixel-buds-pro2",
        title: "Google Pixel Buds Pro 2",
        shortDescription: "Google's best earbuds with Tensor A1 chip.",
        fullDescription:
            "The Google Pixel Buds Pro 2 are powered by the Tensor A1 chip — the first chip Google has designed specifically for audio. Silent Seal 2.0 ANC adapts to your ear canal shape and adjusts 16,000 times per second. Conversation Detection pauses music and switches to Transparency mode when you start talking to someone nearby.",
        category: "Earbuds",
        price: 229.0,
        rating: 4.5,
        imageUrl: "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=600&q=80",
        brand: "Google",
        specs: {
            Chip: "Tensor A1",
            ANC: "Silent Seal 2.0",
            "Battery Life": "8h + 30h case",
            Connectivity: "Bluetooth 5.4 Multipoint",
            "Water Resistance": "IPX4",
            Audio: "Spatial Audio",
            Weight: "6.3g per earbud",
        },
        createdAt: "2025-05-15",
    },
    {
        id: "hyperx-cloud-alpha-wireless",
        title: "HyperX Cloud Alpha Wireless",
        shortDescription: "300-hour battery wireless gaming headset.",
        fullDescription:
            "The HyperX Cloud Alpha Wireless shatters expectations with a staggering 300-hour battery life on a single charge — the longest of any gaming headset. Dual chamber drivers separate bass from mids and highs for distortion-free audio at any volume. The steel and aluminium frame balances durability and comfort for the longest sessions.",
        category: "Gaming",
        price: 199.99,
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1612198790700-0c4cff5c4561?w=600&q=80",
        brand: "HyperX",
        specs: {
            Battery: "300 hours",
            Drivers: "Dual Chamber 50mm",
            Connectivity: "2.4GHz Wireless",
            "Frequency Response": "15Hz–21kHz",
            Microphone: "Detachable noise-cancelling",
            Weight: "335g",
            Frame: "Steel + Aluminium",
        },
        createdAt: "2025-05-18",
    },
    {
        id: "anker-solix-c300",
        title: "Anker SOLIX C300",
        shortDescription: "Portable power station for outdoor and emergency use.",
        fullDescription:
            "The Anker SOLIX C300 is a compact yet powerful portable power station with 288Wh capacity. It charges from 0 to 80% in just 38 minutes using HyperFlash technology. Three AC outlets handle appliances up to 300W while USB-C and USB-A ports charge all your devices simultaneously. The built-in LED light provides emergency illumination.",
        category: "Power",
        price: 399.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&q=80",
        brand: "Anker",
        specs: {
            Capacity: "288Wh",
            "AC Output": "300W (3 outlets)",
            "Fast Charge": "0–80% in 38 min",
            "USB-C": "100W output",
            "USB-A": "12W output",
            LED: "Built-in emergency light",
            Weight: "3.6kg",
        },
        createdAt: "2025-05-20",
    },
    {
        id: "razer-kiyo-pro-ultra",
        title: "Razer Kiyo Pro Ultra",
        shortDescription: "4K Sony STARVIS 2 webcam for professional streaming.",
        fullDescription:
            "The Razer Kiyo Pro Ultra is built for streamers and video professionals who refuse to compromise. The Sony STARVIS 2 sensor captures stunning 4K footage with exceptional dynamic range. AI-powered background removal works in real time without a green screen. The 2.1 aperture lens delivers beautiful background blur comparable to a DSLR.",
        category: "Webcam",
        price: 199.99,
        rating: 4.5,
        imageUrl: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=600&q=80",
        brand: "Razer",
        specs: {
            Resolution: "4K / 30fps, 1080p / 60fps",
            Sensor: "Sony STARVIS 2",
            Aperture: "f/2.1",
            AI: "Background removal",
            HDR: "Yes",
            Connection: "USB-C",
            Software: "Razer Synapse",
        },
        createdAt: "2025-05-22",
    },
    {
        id: "nuphy-air75-v2",
        title: "NuPhy Air75 V2",
        shortDescription: "Ultra-slim low-profile wireless mechanical keyboard.",
        fullDescription:
            "The NuPhy Air75 V2 proves that mechanical keyboards do not have to be thick and heavy. Gateron low-profile switches deliver satisfying tactile feedback at just 3.5mm switch height — half that of standard switches. The slim aluminium deck fits seamlessly into any workspace aesthetic. Three-device Bluetooth with a 4000mAh battery provides weeks of wireless use.",
        category: "Keyboard",
        price: 119.99,
        rating: 4.5,
        imageUrl: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&q=80",
        brand: "NuPhy",
        specs: {
            Switches: "Gateron Low-Profile",
            "Switch Height": "3.5mm",
            Connectivity: "BT 5.0 × 3 / USB-C",
            Battery: "4000mAh",
            Layout: "75%",
            Material: "Aluminium deck",
            Backlight: "RGB",
        },
        createdAt: "2025-05-25",
    },
    {
        id: "sennheiser-momentum-4",
        title: "Sennheiser Momentum 4",
        shortDescription: "60-hour audiophile wireless headphones with ANC.",
        fullDescription:
            "The Sennheiser Momentum 4 Wireless sets a new benchmark for over-ear headphones. A massive 60-hour battery life means you can go weeks between charges. Adaptive Noise Cancellation adjusts based on your environment while the sound signature stays true to Sennheiser's legendary audiophile tuning. Sound Personalization in the Smart Control app tunes the audio profile to your individual hearing.",
        category: "Earbuds",
        price: 349.99,
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1546435770-a3e736e39a2e?w=600&q=80",
        brand: "Sennheiser",
        specs: {
            Battery: "60 hours",
            ANC: "Adaptive Noise Cancellation",
            Drivers: "42mm",
            Connectivity: "Bluetooth 5.2 Multipoint",
            Codec: "aptX Adaptive, AAC, SBC",
            "Fold Design": "Foldable flat",
            Weight: "293g",
        },
        createdAt: "2025-05-28",
    },
    {
        id: "mophie-powerstation-pro-xl",
        title: "Mophie Powerstation Pro XL",
        shortDescription: "20,000mAh wireless + wired charging power bank.",
        fullDescription:
            "The Mophie Powerstation Pro XL is the most versatile power bank Mophie has ever made. A 15W wireless charging pad on the back charges your Qi device without cables while two USB-C ports handle simultaneous wired charging. The premium aluminium housing feels premium in hand and the integrated LED power indicator gives you a precise battery level readout.",
        category: "Power",
        price: 99.99,
        rating: 4.5,
        imageUrl: "https://images.unsplash.com/photo-1609592806596-f1e7aacef00b?w=600&q=80",
        brand: "Mophie",
        specs: {
            Capacity: "20,000mAh",
            Wireless: "15W Qi",
            "USB-C Output": "65W max",
            "USB-A Output": "12W",
            Material: "Aluminium housing",
            Indicator: "LED battery level",
            Weight: "430g",
        },
        createdAt: "2025-05-30",
    },
    {
        id: "asus-rog-ally-x",
        title: "ASUS ROG Ally X",
        shortDescription: "Windows 11 handheld gaming console with AMD Z1 Extreme.",
        fullDescription:
            "The ASUS ROG Ally X is the most powerful handheld gaming PC available. The AMD Ryzen Z1 Extreme processor delivers desktop-class gaming performance in a device that fits in your pocket. A 7-inch 1080p 120Hz display makes games look stunning while the doubled 80Wh battery extends gaming sessions significantly over the original Ally.",
        category: "Gaming",
        price: 799.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600&q=80",
        brand: "ASUS ROG",
        specs: {
            Processor: "AMD Ryzen Z1 Extreme",
            Display: "7in 1080p 120Hz",
            RAM: "24GB LPDDR5",
            Storage: "1TB NVMe SSD",
            Battery: "80Wh",
            OS: "Windows 11",
            Weight: "678g",
        },
        createdAt: "2025-06-01",
    },
    {
        id: "anker-usbc-hub-10in1",
        title: "Anker 10-in-1 USB-C Hub",
        shortDescription: "Single cable connectivity for laptops with 10 ports.",
        fullDescription:
            "The Anker 10-in-1 USB-C Hub turns a single USB-C port into a complete workstation connection. HDMI 2.0 outputs 4K at 60fps to an external monitor while 100W Power Delivery passthrough charges your laptop simultaneously. Gigabit Ethernet, SD and microSD card readers, and four USB-A ports handle every peripheral you own.",
        category: "Accessories",
        price: 65.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=600&q=80",
        brand: "Anker",
        specs: {
            Ports: "10-in-1",
            HDMI: "4K 60Hz",
            "Power Delivery": "100W passthrough",
            Ethernet: "Gigabit",
            "Card Reader": "SD + microSD",
            "USB-A": "4 × USB 3.0",
            Cable: "Integrated USB-C",
        },
        createdAt: "2025-06-03",
    },
    {
        id: "logitech-c922-pro",
        title: "Logitech C922 Pro Stream",
        shortDescription: "1080p 30fps / 720p 60fps webcam for streamers.",
        fullDescription:
            "The Logitech C922 Pro Stream is the go-to webcam for streamers and video creators. It captures silky smooth 60fps footage at 720p for fast-moving content and switches to crisp 1080p at 30fps for interviews and presentations. The dual omni-directional microphones pick up clear audio from across the room and the automatic low-light correction keeps you well lit in any environment.",
        category: "Webcam",
        price: 99.99,
        rating: 4.4,
        imageUrl: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80",
        brand: "Logitech",
        specs: {
            Resolution: "1080p/30fps, 720p/60fps",
            FOV: "78°",
            Microphone: "Dual omni-directional",
            "Low Light": "Auto correction",
            Background: "Background replacement",
            Mount: "Tripod-ready",
            Connection: "USB-A",
        },
        createdAt: "2025-06-05",
    },
];

export function getGadgetById(id) {
    return gadgets.find((g) => g.id === id);
}

export function getRelatedGadgets(currentId, category, limit = 3) {
    return gadgets
        .filter((g) => g.category === category && g.id !== currentId)
        .slice(0, limit);
}