export const CATEGORIES = [
    "All",
    "Earbuds",
    "Smartwatch",
    "Keyboard",
    "Gaming",
    "Power",
    "Accessories",
    "Webcam",
];

export const gadgets = [
    {
        id: "sony-wf1000xm5",
        title: "Sony WF-1000XM5",
        shortDescription: "Industry-leading noise cancellation in a compact form.",
        fullDescription:
            "The Sony WF-1000XM5 sets the gold standard for wireless earbuds. Powered by the QN2e processor, it delivers the most precise noise cancellation Sony has ever put into earbuds. The 8.4mm driver produces expansive sound with deep bass, clear mids, and sparkling highs. LDAC support streams Hi-Res Audio at up to 990kbps over Bluetooth. Speak-to-Chat automatically pauses music when you start talking, and multipoint connection lets you switch seamlessly between two devices.",
        category: "Earbuds",
        price: 279.99,
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80",
        brand: "Sony",
        specs: {
            Connectivity: "Bluetooth 5.3",
            "Battery Life": "8h + 16h case",
            "Noise Cancellation": "QN2e Processor",
            "Driver Size": "8.4mm",
            Weight: "5.9g per earbud",
            Codec: "LDAC, AAC, SBC",
            "Water Resistance": "IPX4",
        },
        createdAt: "2025-01-10",
    },
    {
        id: "apple-watch-ultra2",
        title: "Apple Watch Ultra 2",
        shortDescription: "The most rugged and capable Apple Watch ever made.",
        fullDescription:
            "Built for endurance athletes and adventurers, the Apple Watch Ultra 2 pushes performance to the limit. A 49mm titanium case surrounds the brightest Apple Watch display at 3000 nits, readable in direct sunlight. The dual-frequency GPS provides pinpoint accuracy even in dense canyon terrain. With an 18-hour battery life that extends to 60 hours in Low Power Mode, it will outlast your toughest training days.",
        category: "Smartwatch",
        price: 799.0,
        rating: 4.9,
        imageUrl: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&q=80",
        brand: "Apple",
        specs: {
            Case: "49mm Titanium",
            Display: "3000 nit Always-On Retina",
            Battery: "18h (60h Low Power)",
            GPS: "L1 + L5 Dual Frequency",
            "Water Resistance": "100m",
            Processor: "S9 SiP",
            OS: "watchOS 11",
        },
        createdAt: "2025-01-15",
    },
    {
        id: "keychron-q3-max",
        title: "Keychron Q3 Max",
        shortDescription: "Full aluminum TKL with gasket mount and wireless.",
        fullDescription:
            "The Keychron Q3 Max is the wireless evolution of the beloved Q3 mechanical keyboard. A full CNC-machined aluminum body with a gasket mounting system absorbs the sound and bounce of every keystroke. The south-facing RGB LEDs maximize shine-through on keycaps, and QMK/VIA compatibility means your layout is infinitely customizable. Bluetooth 5.1 connects up to three devices with a single key shortcut.",
        category: "Keyboard",
        price: 199.0,
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
        brand: "Keychron",
        specs: {
            Layout: "TKL (80%)",
            "Mount Type": "Gasket",
            Connectivity: "Bluetooth 5.1 / USB-C",
            Switches: "K Pro Red / Brown / Blue",
            Material: "CNC Aluminum",
            Backlight: "South-facing RGB",
            Battery: "4000mAh",
        },
        createdAt: "2025-01-20",
    },
    {
        id: "razer-deathadder-v3",
        title: "Razer DeathAdder V3",
        shortDescription: "Ergonomic wireless gaming mouse with 90-hour battery.",
        fullDescription:
            "The Razer DeathAdder V3 HyperSpeed is the wireless version of the world's most popular gaming mouse. At just 81g, it retains the iconic ergonomic right-handed shape that millions of players trust. The Focus X 26K optical sensor tracks at up to 26,000 DPI with zero smoothing or acceleration. HyperSpeed wireless technology reduces latency to be on par with wired performance.",
        category: "Gaming",
        price: 99.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=600&q=80",
        brand: "Razer",
        specs: {
            Sensor: "Focus X 26K",
            DPI: "100 – 26,000",
            Connectivity: "HyperSpeed Wireless / USB-C",
            Weight: "81g",
            Battery: "90 hours",
            Buttons: "6 programmable",
            Switches: "3rd Gen Mechanical",
        },
        createdAt: "2025-02-01",
    },
    {
        id: "anker-prime-powerbank",
        title: "Anker Prime 27,650mAh",
        shortDescription: "200W total output power bank for laptops and phones.",
        fullDescription:
            "The Anker Prime is the first power bank capable of delivering 200W of total output power — enough to charge a MacBook Pro at full speed while simultaneously topping up your phone and earbuds. Its 27,650mAh capacity can fill a standard 13-inch laptop twice over. The built-in display shows exact wattage input and output in real time so you always know what's happening.",
        category: "Power",
        price: 149.99,
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80",
        brand: "Anker",
        specs: {
            Capacity: "27,650mAh / 99.35Wh",
            "Max Output": "200W Total",
            Ports: "2× USB-C, 1× USB-A",
            Input: "170W Max",
            Technology: "GaN, ActiveShield 2.0",
            Display: "Smart Digital Display",
            Weight: "652g",
        },
        createdAt: "2025-02-10",
    },
    {
        id: "logitech-brio-505",
        title: "Logitech Brio 505",
        shortDescription: "Full HD webcam with auto-light correction and privacy shutter.",
        fullDescription:
            "The Logitech Brio 505 is engineered for professionals who work from anywhere. Its auto-light balance automatically adjusts exposure in real time, producing clear, bright video whether you're in a dark room or front-lit by a window. The 90° adjustable field of view lets you frame yourself or include a whiteboard. Show Mode flips the camera 180° to share documents on your desk during calls.",
        category: "Webcam",
        price: 129.99,
        rating: 4.5,
        imageUrl: "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=600&q=80",
        brand: "Logitech",
        specs: {
            Resolution: "1080p / 60fps",
            "Field of View": "65°–90° adjustable",
            "Auto Focus": "AI-powered",
            Microphone: "RightSound dual-mic",
            Connection: "USB-C",
            Privacy: "Built-in shutter",
            Compatibility: "Windows, macOS, ChromeOS",
        },
        createdAt: "2025-02-18",
    },
    {
        id: "samsung-galaxy-buds3-pro",
        title: "Samsung Galaxy Buds3 Pro",
        shortDescription: "Open-canal design with intelligent ANC and 360 Audio.",
        fullDescription:
            "Samsung's Galaxy Buds3 Pro reinvent the premium earbud with a blade-inspired open-canal design that sits comfortably without the sealed feeling of traditional ANC earbuds. Intelligent Active Noise Cancellation analyzes your environment 240 times per second. 360 Audio with head tracking follows the motion of your head for a true spatial listening experience.",
        category: "Earbuds",
        price: 249.99,
        rating: 4.6,
        imageUrl: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80",
        brand: "Samsung",
        specs: {
            Design: "Open-canal blade",
            Driver: "10.5mm two-way",
            "Battery Life": "6h + 18h case",
            ANC: "Intelligent ANC 3.0",
            Codec: "SSC HiFi, AAC, SBC",
            "Water Resistance": "IPX7",
            Connectivity: "Bluetooth 5.4",
        },
        createdAt: "2025-03-01",
    },
    {
        id: "elgato-stream-deck-mk2",
        title: "Elgato Stream Deck MK.2",
        shortDescription: "15 LCD keys to control your stream, apps, and workflow.",
        fullDescription:
            "The Elgato Stream Deck MK.2 puts 15 customizable LCD keys at your fingertips. Each key can show any icon or image and trigger any action with a single tap — launch apps, switch scenes in OBS, play audio clips, or control smart lights. Unlimited page nesting means you can store hundreds of actions across themed pages. The detachable faceplate lets you swap in custom designs.",
        category: "Accessories",
        price: 149.99,
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=600&q=80",
        brand: "Elgato",
        specs: {
            Keys: "15 customizable LCD",
            Resolution: "72×72px per key",
            Connection: "USB-C",
            Compatibility: "Windows 10+, macOS 10.15+",
            Software: "Stream Deck Software",
            Stand: "Adjustable, reversible",
            Dimensions: "118×84×21mm",
        },
        createdAt: "2025-03-10",
    },
    {
        id: "garmin-forerunner-965",
        title: "Garmin Forerunner 965",
        shortDescription: "Premium AMOLED running smartwatch with full triathlon support.",
        fullDescription:
            "The Garmin Forerunner 965 is built for athletes who demand data. The vibrant AMOLED display is always on without sacrificing the 31-day battery life in smartwatch mode. Training Readiness synthesizes your sleep, HRV, and recent training load into a single daily score. Advanced race predictor uses real performance data to tell you your true capability across distances from 5K to marathon.",
        category: "Smartwatch",
        price: 599.99,
        rating: 4.8,
        imageUrl: "https://images.unsplash.com/photo-1523475496153-3e2b9b518c5f?w=600&q=80",
        brand: "Garmin",
        specs: {
            Display: "AMOLED Always-On",
            Battery: "31 days / 19h GPS",
            GPS: "Multi-band GNSS",
            "Health Sensors": "HRV, SpO2, Pulse Ox",
            "Water Resistance": "100m",
            Storage: "32GB music",
            Weight: "53g",
        },
        createdAt: "2025-03-15",
    },
    {
        id: "steelseries-arctis-nova-pro",
        title: "SteelSeries Arctis Nova Pro",
        shortDescription: "Hi-Fi gaming headset with active noise cancellation.",
        fullDescription:
            "The SteelSeries Arctis Nova Pro is the most technically advanced gaming headset SteelSeries has ever produced. High-fidelity 40mm neodymium drivers cover the full 10–40,000Hz spectrum. Active Noise Cancellation rivals dedicated consumer earbuds. The hot-swap battery system means you will never be pulled out of a game to charge — one battery charges in the case while the other powers the headset.",
        category: "Gaming",
        price: 349.99,
        rating: 4.7,
        imageUrl: "https://images.unsplash.com/photo-1599669454699-248893623440?w=600&q=80",
        brand: "SteelSeries",
        specs: {
            Drivers: "40mm Hi-Fi neodymium",
            "Frequency Response": "10–40,000Hz",
            ANC: "Active Noise Cancellation",
            Connectivity: "Bluetooth 5.0 + 2.4GHz",
            Battery: "Hot-swap dual battery",
            Microphone: "ClearCast Gen 2 retractable",
            Weight: "338g",
        },
        createdAt: "2025-03-20",
    },
];

export function getGadgetById(id) {
    return gadgets.find((g) => g.id === id);
}

export function getRelatedGadgets(currentId, category, limit = 3) {
    return gadgets
        .filter((g) => g.category === category && g.id !== currentId)
        .slice(0, limit);
}